fail_fast = true

[[repos]]
repo = "local"
hooks = [
  { id = "typos", name = "typos", language = "system", entry = "typos", pass_filenames = false },
  { id = "zola-check", name = "zola check", language = "system", entry = "zola check --skip-external-links", pass_filenames = false },
  { id = "zola-build", name = "zola build", language = "system", entry = "zola build", pass_filenames = false },
  { id = "gitleaks", name = "gitleaks", language = "system", entry = "gitleaks git --verbose", pass_filenames = false },
]
